### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by annihilatorrrr** [divideprojects/UtilitiesRoBot#27]
- [ ] more utilities such so that PPL can use it in groups ( backend )
- [ ] make all git related things ( download and gits , gist too.) make use of https://github.com/gitpython-developers/GitPython
- [ ] make image search, google, dictionary ( inline too ), wiki, lyrics, doge sticker XD too
